basePath: /api/v1
definitions:
  main.User:
    properties:
      age:
        type: integer
      name:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: follenlast2@gmail.com
  description: Example of API with swaggo
  title: Swagger Example API
  version: "1.0"
paths:
  /name:
    get:
      parameters:
      - description: User input
        in: path
        name: input
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: Name
      tags:
      - ping
  /ping:
    get:
      parameters:
      - description: User input
        in: path
        name: input
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      security:
      - ApiKey: []
      summary: Ping
      tags:
      - ping
securityDefinitions:
  ApiKey:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
